### ISSUE TITLE
Configure HTTP Strict Transport Security (HSTS)

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-keycloak#5]
Configure the proper proxy headers to instruct the browser to use always HTTPS

https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet
https://caniuse.com/#feat=stricttransportsecurity

**Comment by dlebrero** [comment]
What if we disallow HTTP traffic at the ingress level? Maybe then we can apply the same solution to all services.

See https://stackoverflow.com/questions/40763718/kubernetes-https-ingress-in-google-container-engine

**Comment by dlebrero** [comment]
Applied the above in TEST. HTTP now returns 404

**Comment by iperdomo** [comment]
That's good progress, how can we hint _modern_ browers to always access this via HTTPS ?
At some point i tried to do redirect 80 -> 443 at `web.xml` in Keycloak, but didn't manage it to do it properly.

**Comment by dlebrero** [comment]
We are going to get rid of Keycloak
